# Generated by Django 6.0.2 on 2026-02-13 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_worker_assigned_to_complaint_assigned_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='assigned_worker',
        ),
        migrations.AddField(
            model_name='worker',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_worker', to='api.complaint'),
        ),
    ]
