# Generated by Django 6.0.2 on 2026-02-15 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_complaint_assigned_worker_worker_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='role',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='worker',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_workers', to='api.complaint'),
        ),
    ]
