# Generated by Django 6.0.1 on 2026-02-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_adminuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='image',
            field=models.ImageField(default='null', upload_to='image/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
    ]
