# Generated by Django 6.0.1 on 2026-02-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_complaint_image_complaint_is_urgent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='is_urgent',
            field=models.BooleanField(default='False'),
        ),
    ]
