# Generated by Django 6.0.2 on 2026-03-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_worker_assigned_to_complaint_assigned_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='phone_no',
            field=models.CharField(default='-', max_length=15),
        ),
    ]
