# Generated by Django 6.0.1 on 2026-02-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_complaint_is_urgent'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='Department',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='complaints/'),
        ),
    ]
